### PR TITLE
Fix for issue 35

### PR DESCRIPTION
**Pull request by mobinni**
fixed function regex, it now takes in the function name on its own, this leads to no () being shown, however this is not necessary for the constructor name

### CODE REVIEW

**Comment by mohsen1** [comment]
Thanks for this. Can you write a few tests that validates this? Regex can be tricky.

**Comment by mobinni** [comment]
I can, do you have any tests for reference?

**Comment by mohsen1** [comment]
Just test that confirms this works. Similar to your example.

**Comment by mobinni** [comment]
Done 👍

**Comment by mohsen1** [comment]
Thanks!

**Pull request merged**
