### PR TITLE
Make webpack play better with browserify

### PR DESCRIPTION
**Pull request by andyburke**
This change will cause a dead code path that would cause browserify problems to be removed. The dead code path had to do with hot module reloading, which appeared to be turned off, but browserify would still find the require() statement with a weird file path in it.

This change also seems to shave a good 15KB off the dist file by running it through UglifyJS, even without any compression or mangling (probably due to comment removal).

Willing to discuss, but this fixed things so I could use this with my browserify setup.

### CODE REVIEW

**Comment by andyburke** [comment]
@mohsen1 any guidance? I've fixed various configuration issues with updating webpack/karma-webpack/etc, but I'm not sure what's up with the tests now?

**Comment by mohsen1** [comment]
Let me checkout the branch and see

**Comment by mohsen1** [comment]
Funny tests pass on my machine! Not sure what's going on?


I was thinking of switching to yarn for this project. Do you want to do that as well?

**Comment by andyburke** [comment]
I'm not sure I have time to undertake much more work on this for now. These changes make the project work for me in our browserify-based SPA. We're currently using my branch. Would love to get these changes mainlined and switch back to the npm-published version.

**Comment by mohsen1** [comment]
I'll try to merge and publish this soon

**Comment by Xstoudi** [comment]
Please, really need this pull request to be merged.

**Comment by mohsen1** [comment]
Released at version 2.0 

Let me know if you have any problems

**Pull request merged**
