### PR TITLE
Remove dist folder from repo

### PR DESCRIPTION
**Pull request by juanjoDiaz**
The `dist` folder shouldn't be part of the repo.
It should be created by Travis during the build process.
I'm happy to help with that if there is any issue with the current build setup.

### CODE REVIEW

**Comment by mohsen1** [comment]
this is Bower legacy. Good callout to clean this up.

**Comment by juanjoDiaz** [comment]
Is it ok to remove the bower file as well since bower is officially deprecated?

**Comment by alasdairhurst** [comment]
Looks like this was reverted/undone with the merges that were done afterwards. Dist needs removing again.

**Comment by mohsen1** [comment]
Thanks for the heads up @alasdairhurst, removed 1ea395f82329d74cac0293c6d13a619eda081330

**Pull request merged**
