### PR TITLE
Option to sort properties

### LINKED ISSUE #30: Option to sort properties
It will be a nice option to add. Example:

current behavior:

``` json
{
  "a": 1,
  "c": 2,
  "b": {
      "z": 1,
      "y": 2
   }
}
```

With sorting option (ascending/descending flavors):

``` json
{
  "a": 1,
  "b": {
      "y": 2,
      "z": 1
   },
  "c": 2,
}
```

Note that we sort inside the nested objects too.

Why is this useful?
Sorting imposes an automatic grouping on the similar properties.
Example currently similar properties are seen as:

``` JSON
{
  "ui.filter.params":null,
  "storm.messaging.netty.client_worker_threads":1,
  "ui.actions.enabled":true,
  "storm.cluster.mode":"distributed",
  "zmq.linger.millis":5000,
  "supervisor.enable":true
}
```

This is very inconvenient and a sort option will really make it easy to read.

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Closes #30

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
The build failure seems to be related to yarn and not to my change. @mohsen1 maybe you can take a look :)

**Comment by mohsen1** [comment]
Thought this is an error due to npm registry failure that was going on yesterday but it's still persisting.

```
error An unexpected error occurred: "https://registry.yarnpkg.com/pinkie/-/pinkie-2.0.5.tgz: Request failed \"404 Not Found\"".
```

I'll investigate a bit more

**Comment by mohsen1** [comment]
yep, this package is still missing from the registry. At the time of writing this comment:

```
 yarn info pinkie versions                               535ms  Sun Jan  7 10:09:23 2018
yarn info v1.3.2
[ '0.0.0',
  '0.0.1',
  '0.0.2',
  '1.0.0',
  '2.0.0',
  '2.0.1',
  '2.0.2',
  '2.0.3',
  '2.0.4' ]
```

**Comment by mohsen1** [comment]
I will publish this after master is green

**Pull request merged**
