### PR TITLE
Fix collapse bug

### PR DESCRIPTION
**Pull request by jomido**
When you collapse a node in the output tree, you'd forever after lose all of the children. i.e. you couldn't get them back after a collapse. This small change remedies this, so that nodes in the tree rebuild themselves when you 'open' them again.

### CODE REVIEW

**Comment by mohsen1** [comment]
I don't see why and how this helps?

**Comment by jomido** [comment]
Hi Mohsen,

Thank you for the reply. 

In the addChildern() [sic] function there is a check to see if 'div.children' exists: [here](https://github.com/mohsen1/json-formatter-js/blob/master/src/index.ts#L310).

If one calls removeChildren() previously to this, then 'div.children' no longer exists: see [here](https://github.com/mohsen1/json-formatter-js/blob/master/src/index.ts#L325).

So it appears to me that after having removed the children by toggling a node to a closed state, there is no way that the children will be added again by addChildern() [sic] because of the early exit on line 310.

At least, this is the behavior that I see in latest Chrome (48): after a collapse of child nodes, they will no longer re-insert when you attempt to uncollapse them.

Are you not seeing this same behavior?

**Comment by mohsen1** [comment]
Current master is broken since I was trying to use TypeScript and there was some issues with TS and globals. I need to finish that work. So I can't confirm if the issue you're referring to exists.

In the latest release, everything is working as expected. You can see it in action [here](http://azimi.me/json-formatter-js/demo/)

**Comment by jomido** [comment]
OK, thank you Mohsen.

**Pull request closed without merging**
